# Generated by Django 4.1.5 on 2023-02-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_alter_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director_email',
        ),
    ]
